apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ .Values.control_plane_name }}
  namespace: {{ .Values.control_plane_namespace }}
spec:
  version: v2.0
  tracing:
    sampling: 10000
    type: Jaeger
  gateways:
    enabled: true
    egress:
      enabled: true
      runtime:
        deployment:
          replicas: 1
    ingress:
      enabled: true
      runtime:
        deployment:
          replicas: 1
    openshiftRoute:
            enabled: false
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.0
  telemetry:
    type: Istiod
