apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
  namespace: {{ .Values.control_plane_namespace }}
spec:
  port:
    targetPort: http2
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
