apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh-operator
spec:
  channel: "1.0"
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

