{{- if $.Values.mtls }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
  {{- if $.Values.permissive }}
    mode: PERMISSIVE
  {{- else if $.Values.mtlsdisable }}
    mode: DISABLE
  {{- else}}
    mode: STRICT
  {{- end }}
{{- end }}
